# Generated by Django 4.1.4 on 2022-12-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserFirstName', models.CharField(max_length=100)),
                ('UserLastName', models.CharField(max_length=100)),
            ],
        ),
    ]
