# Generated by Django 4.1.4 on 2022-12-07 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DateOfJoining',
            field=models.DateField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
